### ISSUE TITLE
File not found: Box2d\box2d.json (Internal)

### ISSUE THREAD

**Issue by whiletrue111** [mkoenig-dev/TroubledRowers#1]
When executing from android studio the desktop project getting this 

```
> Task :desktop:DesktopLauncher.main() FAILED
[GS_NOOP] Connect called, silent: true
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: File not found: Box2d\box2d.json (Internal)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:142)
	at com.badlogic.gdx.files.FileHandle.length(FileHandle.java:641)
	at com.badlogic.gdx.files.FileHandle.estimateLength(FileHandle.java:239)
	at com.badlogic.gdx.files.FileHandle.readString(FileHandle.java:204)
	at com.badlogic.gdx.files.FileHandle.readString(FileHandle.java:197)
	at aurelienribon.bodyeditor.BodyEditorLoader.<init>(BodyEditorLoader.java:48)
	at com.samb.trs.Controllers.AssetController.<init>(AssetController.java:32)
	at com.samb.trs.Controllers.MainController.<init>(MainController.java:26)
	at com.samb.trs.GameApplication.create(GameApplication.java:18)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:416)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:366)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
	at com.samb.trs.desktop.DesktopLauncher.main(DesktopLauncher.java:14)

Execution failed for task ':desktop:DesktopLauncher.main()'.
> Process 'command 'C:/Program Files/Android/Android Studio/jbr/bin/java.exe'' finished with non-zero exit value 1
```

**Comment by mlkoenig** [comment]
Hi, the repository only contains the project structure and code, not the game assets.
I plan to host a demo html version in the future if you're interested in trying the game.
